server:
  port: 5000

springdoc:
   api-docs:
      path: /api-docs
      doc-expansion: none
   swagger-ui:
      path: /swagger-api-docs.html
      supportedSubmitMethods: ["get"]
      doc-expansion: none

spring:
   application:
      name: API
   datasource:
      url: jdbc:postgresql://localhost:5432/Stageopdracht
      username: user
      password: admin
   mvc:
     async:
        request-timeout: -1

   kafka:
      topicFeedback: Kiten.Feedback
      topicSubscription: Kiten.subscription
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      client.dns.lookup: use_all_dns_ips
      session.timeout.ms: 45000
      basic.auth.credentials.source: USER_INFO
    
      consumer:
         bootstrapServer: http://localhost:9092
         specificAvroReaderConfig: true
         groupId: adapter_mvb
         autoOffsetReset: earliest
         enableAutoCommit: true
         keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
         valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
         schemaRegistry: http://localhost:8081
      
      producer:
         bootstrapServer: http://localhost:9092
         acks: all
         retries: 0
         keySerializer: org.apache.kafka.common.serialization.StringSerializer
         valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
         schemaRegistry: http://localhost:8081
         valueSubjectNameStrategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

email:
   host: localhost
   port: 1025
   username: username
   password: password
