server:
  port: 5000

springdoc:
   api-docs:
      path: /api-docs
      doc-expansion: none
   swagger-ui:
      path: /swagger-api-docs.html
      supportedSubmitMethods: ["get"]
      doc-expansion: none

spring:
   application:
      name: API
   datasource:
      url: jdbc:postgresql://localhost:5432/Stageopdracht
      username: user
      password: admin
   mvc:
     async:
        request-timeout: -1

   kafka:
      bootstrap-servers: localhost:9092
      topicFeedback: Kiten.Feedback
      topicSubscription: Kiten.subscription
      
      properties:      
         schema.registry.url: http://localhost:8081
         specific.avro.reader: true
      
    
      consumer:
         keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
         valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
         
         groupId: adapter_mvb
         autoOffsetReset: earliest
         enableAutoCommit: true
      
      producer:
         keySerializer: org.apache.kafka.common.serialization.StringSerializer
         valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
         valueSubjectNameStrategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
         
         acks: all
         retries: 0

email:
   host: localhost
   port: 1025
   username: username
   password: password
