server:
  port: 1083

spring:
  application:
    name: API
  datasource:
    url: jdbc:postgresql://localhost:5432/Stageopdracht
    username: user
    password: admin

  kafka:
    topic: Kiten.Feedback
    consumer:
      bootstrapServer: http://localhost:9092
      specificAvroReaderConfig: true
      groupId: adapter_mvb
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schemaRegistry: http://localhost:8081

    producer:
      bootstrapServer: http://localhost:9092
      acks: all
      retries: 0
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schemaRegistry: http://localhost:8081
